// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IMce-dCRtyiC4Q3N-JRZ7RlWWAH0m8M',
    appId: '1:974147774933:web:7708a92dc2be84a47d755c',
    messagingSenderId: '974147774933',
    projectId: 'evcar-48b5e',
    authDomain: 'evcar-48b5e.firebaseapp.com',
    storageBucket: 'evcar-48b5e.appspot.com',
    measurementId: 'G-E6HMQ7Z496',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjXh_mHY7qvC0ovJ2nC_umdfSwyKe-PJs',
    appId: '1:974147774933:android:9287c139630164f17d755c',
    messagingSenderId: '974147774933',
    projectId: 'evcar-48b5e',
    storageBucket: 'evcar-48b5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTAjUHYofO6XbnYSoB2f-sVNGr05NE0U',
    appId: '1:974147774933:ios:0704eb4713ec228e7d755c',
    messagingSenderId: '974147774933',
    projectId: 'evcar-48b5e',
    storageBucket: 'evcar-48b5e.appspot.com',
    iosBundleId: 'com.example.evcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTAjUHYofO6XbnYSoB2f-sVNGr05NE0U',
    appId: '1:974147774933:ios:18c5bd4b0995e5337d755c',
    messagingSenderId: '974147774933',
    projectId: 'evcar-48b5e',
    storageBucket: 'evcar-48b5e.appspot.com',
    iosBundleId: 'com.example.evcar.RunnerTests',
  );
}
